# Generated by Django 3.1.5 on 2021-01-24 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameOpenings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openingName', models.CharField(max_length=900)),
                ('games', models.CharField(max_length=900)),
                ('openingEco', models.CharField(max_length=900)),
                ('whiteRating', models.IntegerField()),
                ('blackRating', models.IntegerField()),
                ('winner', models.CharField(max_length=900)),
                ('totalStrength', models.IntegerField()),
            ],
        ),
    ]
